### ISSUE TITLE
P5 code is not showed as code but text

### ISSUE THREAD

**Issue by AnnMic** [MakeSchool-Tutorials/Sushi-Neko-SpriteKit-Swift#5]
There is probably a typo in the playground. The code on the section "Moving the tower" is shown as text and not as code.

**Comment by etodd** [comment]
Maybe this has been fixed already? It looks good to me.

**Moving the tower**

> [action]
> Add the following code after the last block:
> 
> ```
> /* Drop all the sushi pieces down one place */
> for node:SushiPiece in sushiTower {
>   node.runAction(SKAction.moveBy(CGVector(dx: 0, dy: -55), duration: 0.10))
> 
>   /* Reduce zPosition to stop zPosition climbing over UI */
>   node.zPosition -= 1
> }
> ```
